### PR TITLE
Jsdeliver

### PR DESCRIPTION
**Pull request by nicolashefti**
Include the built library into the repository for further accessibility on CDN like jsdeliver.

### CODE REVIEW

**Comment by nicolashefti** [comment]
Hi @jalateras, any question/comment on the PR?

**Comment by jalateras** [comment]
@nicolashefti I will look t it in the next couple of days

**Comment by jalateras** [comment]
@nicolashefti 

Getting the following errors on build

```
Hash: af0024a4e35c795119f2
Version: webpack 1.13.2
Time: 21ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./core in /Users/jima/stoic/workspace/formula.js
Hash: 396c152fa7f618115f27
Version: webpack 1.13.2
Time: 21ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./core in /Users/jima/stoic/workspace/formula.js
Hash: 8fa7816a6aaa9e6cfaf3
Version: webpack 1.13.2
Time: 20ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./core in /Users/jima/stoic/workspace/formula.js
Hash: b98499c009c2b1d613f9
Version: webpack 1.13.2
Time: 21ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./core in /Users/jima/stoic/workspace/formula.js
```

**Comment by jalateras** [comment]
Looks like you may have forgotten to check `core` in. Is it JS file or library or .....

**Comment by nicolashefti** [comment]
@jalateras, I renamed ./index.js to ./lib/core.js to avoid having JS files at the root of the repository. Then I just ran 'make test' which did not trigger any error...

That being said I rollbacked this change which is unrelevant for the current PR. The build is now working on my side.

**Pull request merged**
