### PR TITLE
fixed a bug in MID function - substring was incorrectly used

### PR DESCRIPTION
**Pull request by greyarch**
The signature of substring is text.substring(begin, end), as opposed to MID(text, start, numberOfCharsToReturn).

### CODE REVIEW

**Comment by greyarch** [comment]
Hey Jim,
  Thanks for the swift merge. How about a new npm package version with this fix?
Cheers!

**Comment by jalateras** [comment]
I have published  1.0.7

**Comment by greyarch** [comment]
The npm website still reports 1.0.6 as the latest version. npm install also gets 1.0.6

**Comment by jalateras** [comment]
Check again, it should be there.

**Comment by hmalphettes** [comment]
Thanks Jim! I can see it now.

**Pull request merged**
