### PR TITLE
Add support 0.1 + 0.2.

### PR DESCRIPTION
**Pull request by GGICE**
Add support 0.1 + 0.2 = 0.3 , like this sum.

### CODE REVIEW

**Comment by stevebroshar** [comment]
SUM already returns (approx) .3 for .1+.2.  Is this change about getting it to return _exactly_ .3?

IMHO, looks like the code to implement this is relatively time-consuming.  The result is nice, but I don't think the juice is worth the squeeze.  Floating point math is always assumed to have rounding errors -- which can be handled in a variety of ways.  In excel for example, the display format generally handles this by rounding to a small number of decimal places - 0, 1 or 2 usually.

**Comment by GGICE** [comment]
But, like we input `=SUM(0.1,0.2)` in Excel or google Excel ,the result is 0.3 not 0.30000000000000004 ,so I think we should do something to solve those float sum math, even if my method is not necessarily good.

**Comment by spelunk** [comment]
@GGICE .1 + .2 is not .3 according to IEEE754, it's actually the same `0.30000000000000004` that you get if you do it in JS or python or pretty much any programming language whose implementation falls back to hardware floating point.

If you are concerned about the Excel display, [a third-party library](https://github.com/SheetJS/ssf) does that part

**Comment by GGICE** [comment]
TKS, I will try.

**Pull request closed without merging**
